<?php
return [
		'bootstrap'=>[
				'composer'=>['twitter/bootstrap'=>'^4.3','fortawesome/font-awesome'=>'^5.7'],
				'vendor-copy'=>[
						'./../vendor/fortawesome/font-awesome/css/all.min.css'=>'./../public/assets/bootstrap/css/all.min.css',
						'./../vendor/fortawesome/font-awesome/webfonts'=>'./../public/assets/bootstrap/',
				],
				'xcopy'=>['bootstrap/'=>'app/views/themes/']
		],
		'foundation'=>[
				'composer'=>['zurb/foundation'=>'^6.5']
		],
		'semantic'=>[
				'composer'=>['semantic/ui'=>'^2.4'],
				'vendor-copy'=>[
						'./../vendor/semantic/ui/dist/semantic.min.css'=>'./../public/assets/semantic/css/',
						'./../vendor/semantic/ui/dist/semantic.min.js'=>'./../public/assets/semantic/js/'
				]
		]
];